const proffys = [
    { name: "Kesley Lima", avatar: "https://avatars2.githubusercontent.com/u/2254731?s=460&amp;u=0ba16a79456c2f250e7579cb388fa18c5c2d7d65&amp;v4", whatsapp:"9494", bio:"paixonado por explodir coisas em laboratório e por mudar a vida das pessoas através de experiências. Mais de 200.000 pessoas já passaram por uma das minhas explosões", subject:"Quimica", cost:"20", weekday: [0], time_from: [700], time_to: [1200]  
    },

    { name: "Kesley Psyteck", avatar: "https://avatars2.githubusercontent.com/u/2254731?s=460&amp;u=0ba16a79456c2f250e7579cb388fa18c5c2d7d65&amp;v4", whatsapp:"9494", bio:"paixonado por<br><br> expl20151515odir coisas em laboratório e por ssssmudar a vida das pessoas através de experiências. Mais de 200.000 pessoas já passaram por uma das minhas explo2sões", subject:"Matemática", cost:"20", weekday: [8], time_from: [700], time_to: [1200]  
    }
]